/**
 * Path/query parameter validators for the REST routes.
 *
 * Keep these tiny and dependency-free: zod is fine for body schemas, but
 * one-shot regex checks on path/query params are faster to read and write.
 *
 * Each validator returns the normalized value on success or null on failure.
 * Route handlers turn `null` into `handleError(reply, 400, ..., 'INVALID_PARAM')`.
 */

const WALLET_RX = /^0x[a-fA-F0-9]{40}$/;
const TOKEN_RX = /^[0-9]{1,78}$/;
const CERT_RX = /^(PSA|BGS|CGC|SGC)\d{6,12}$/i;
// cuid v1 is `c` + 24 chars total (lowercase alnum). cuid v2 is 24 lowercase alnum.
// Accept both 24-25 char shapes.
const CUID_RX = /^[a-z0-9]{24,30}$/i;
// NanoID: 21-char URL-safe alphabet (A-Z, a-z, 0-9, `-`, `_`). Pull IDs are
// generated by `nanoid()` in `pull-upsert.ts` (not Prisma's cuid()), so the
// pullId validator must accept this shape.
const NANOID_RX = /^[A-Za-z0-9_-]{21}$/;
// UUID v4 (or any-version) — the Renaiss item id shape (rid). Matches
// `items.renaiss_item_id` per the Index API openapi.json example
// `12670e6b-f07a-4a56-bc37-4f5e42edc6a8`.
const UUID_RX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export const validateTokenId = (raw: unknown): string | null => {
  if (typeof raw !== 'string') return null;
  const trimmed = raw.trim();
  if (!TOKEN_RX.test(trimmed)) return null;
  return trimmed;
};

export const validateWalletAddress = (raw: unknown): string | null => {
  if (typeof raw !== 'string') return null;
  const trimmed = raw.trim();
  if (!WALLET_RX.test(trimmed)) return null;
  return trimmed.toLowerCase();
};

export const validateCert = (raw: unknown): string | null => {
  if (typeof raw !== 'string') return null;
  const trimmed = raw.trim();
  if (!CERT_RX.test(trimmed)) return null;
  return trimmed.toUpperCase();
};

export const validateRenaissId = (raw: unknown): string | null => {
  if (typeof raw !== 'string') return null;
  const trimmed = raw.trim();
  if (!UUID_RX.test(trimmed)) return null;
  return trimmed.toLowerCase();
};

export const validatePullId = (raw: unknown): string | null => {
  if (typeof raw !== 'string') return null;
  const trimmed = raw.trim();
  // Pull IDs are NanoIDs (via `pull-upsert.ts`), but fall back to CUID
  // acceptance so any legacy rows still resolve.
  if (!NANOID_RX.test(trimmed) && !CUID_RX.test(trimmed)) return null;
  return trimmed;
};

export const validateCursor = (raw: unknown): string | null | undefined => {
  if (raw === undefined || raw === null || raw === '') return undefined;
  if (typeof raw !== 'string') return null;
  const trimmed = raw.trim();
  if (trimmed.length === 0) return undefined;
  if (!NANOID_RX.test(trimmed) && !CUID_RX.test(trimmed)) return null;
  return trimmed;
};

/**
 * Coerce a query-string `limit` parameter into an integer in [min, max].
 * Returns null on parse failure or out-of-range so callers can 400.
 */
export const validateLimit = (
  raw: unknown,
  defaultValue: number,
  min: number,
  max: number
): number | null => {
  if (raw === undefined || raw === null || raw === '') return defaultValue;
  const asNum = typeof raw === 'number' ? raw : Number(raw);
  if (!Number.isFinite(asNum)) return null;
  const asInt = Math.floor(asNum);
  if (asInt < min || asInt > max) return null;
  return asInt;
};

/**
 * Shape returned to the client for every Pull list/single response. Excludes
 * rawAttributesJson and internal-only fields. Matches the brief's projection
 * list exactly.
 */
export interface PullPublicProjection {
  id: string;
  packSlug: string;
  collectibleTokenId: string;
  buyerAddress: string;
  tier: string | null;
  fmvUsdCents: number | null;
  packPriceUsdCents: number;
  netGainUsdCents: number | null;
  pulledAtTimestamp: Date;
  cardName: string | null;
  setName: string | null;
  cardNumber: string | null;
  gradingCompany: string | null;
  grade: string | null;
  serial: string | null;
  frontImageUrl: string | null;
  shareCardPostedAt: Date | null;
  createdAt: Date;
}

/**
 * Prisma `select` clause matching the public projection above. Used by every
 * Pull-returning route to guarantee we never leak `rawAttributesJson`,
 * `txHash`, `blockNumber`, `backImageUrl`, or `updatedAt`/`deletedAt`.
 */
export const PULL_PUBLIC_SELECT = {
  id: true,
  packSlug: true,
  collectibleTokenId: true,
  buyerAddress: true,
  tier: true,
  fmvUsdCents: true,
  packPriceUsdCents: true,
  netGainUsdCents: true,
  pulledAtTimestamp: true,
  cardName: true,
  setName: true,
  cardNumber: true,
  gradingCompany: true,
  grade: true,
  serial: true,
  frontImageUrl: true,
  shareCardPostedAt: true,
  createdAt: true,
} as const;
