/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PriceRouteImport } from './routes/price'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as MarketRouteImport } from './routes/market'
import { Route as FeaturedRouteImport } from './routes/featured'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AddressRouteImport } from './routes/$address'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardTxRouteImport } from './routes/card.$tx'
import { Route as SetsGameSetRouteImport } from './routes/sets.$game.$set'
import { Route as CardGameSetCardRouteImport } from './routes/card.$game.$set.$card'

const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceRoute = PriceRouteImport.update({
  id: '/price',
  path: '/price',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedRoute = FeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressRoute = AddressRouteImport.update({
  id: '/$address',
  path: '/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardTxRoute = CardTxRouteImport.update({
  id: '/card/$tx',
  path: '/card/$tx',
  getParentRoute: () => rootRouteImport,
} as any)
const SetsGameSetRoute = SetsGameSetRouteImport.update({
  id: '/sets/$game/$set',
  path: '/sets/$game/$set',
  getParentRoute: () => rootRouteImport,
} as any)
const CardGameSetCardRoute = CardGameSetCardRouteImport.update({
  id: '/card/$game/$set/$card',
  path: '/card/$game/$set/$card',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$address': typeof AddressRoute
  '/browse': typeof BrowseRoute
  '/ecosystem': typeof EcosystemRoute
  '/featured': typeof FeaturedRoute
  '/market': typeof MarketRoute
  '/packs': typeof PacksRoute
  '/price': typeof PriceRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/trades': typeof TradesRoute
  '/card/$tx': typeof CardTxRoute
  '/sets/$game/$set': typeof SetsGameSetRoute
  '/card/$game/$set/$card': typeof CardGameSetCardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$address': typeof AddressRoute
  '/browse': typeof BrowseRoute
  '/ecosystem': typeof EcosystemRoute
  '/featured': typeof FeaturedRoute
  '/market': typeof MarketRoute
  '/packs': typeof PacksRoute
  '/price': typeof PriceRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/trades': typeof TradesRoute
  '/card/$tx': typeof CardTxRoute
  '/sets/$game/$set': typeof SetsGameSetRoute
  '/card/$game/$set/$card': typeof CardGameSetCardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$address': typeof AddressRoute
  '/browse': typeof BrowseRoute
  '/ecosystem': typeof EcosystemRoute
  '/featured': typeof FeaturedRoute
  '/market': typeof MarketRoute
  '/packs': typeof PacksRoute
  '/price': typeof PriceRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/trades': typeof TradesRoute
  '/card/$tx': typeof CardTxRoute
  '/sets/$game/$set': typeof SetsGameSetRoute
  '/card/$game/$set/$card': typeof CardGameSetCardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$address'
    | '/browse'
    | '/ecosystem'
    | '/featured'
    | '/market'
    | '/packs'
    | '/price'
    | '/search'
    | '/stats'
    | '/trades'
    | '/card/$tx'
    | '/sets/$game/$set'
    | '/card/$game/$set/$card'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$address'
    | '/browse'
    | '/ecosystem'
    | '/featured'
    | '/market'
    | '/packs'
    | '/price'
    | '/search'
    | '/stats'
    | '/trades'
    | '/card/$tx'
    | '/sets/$game/$set'
    | '/card/$game/$set/$card'
  id:
    | '__root__'
    | '/'
    | '/$address'
    | '/browse'
    | '/ecosystem'
    | '/featured'
    | '/market'
    | '/packs'
    | '/price'
    | '/search'
    | '/stats'
    | '/trades'
    | '/card/$tx'
    | '/sets/$game/$set'
    | '/card/$game/$set/$card'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressRoute: typeof AddressRoute
  BrowseRoute: typeof BrowseRoute
  EcosystemRoute: typeof EcosystemRoute
  FeaturedRoute: typeof FeaturedRoute
  MarketRoute: typeof MarketRoute
  PacksRoute: typeof PacksRoute
  PriceRoute: typeof PriceRoute
  SearchRoute: typeof SearchRoute
  StatsRoute: typeof StatsRoute
  TradesRoute: typeof TradesRoute
  CardTxRoute: typeof CardTxRoute
  SetsGameSetRoute: typeof SetsGameSetRoute
  CardGameSetCardRoute: typeof CardGameSetCardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price': {
      id: '/price'
      path: '/price'
      fullPath: '/price'
      preLoaderRoute: typeof PriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured': {
      id: '/featured'
      path: '/featured'
      fullPath: '/featured'
      preLoaderRoute: typeof FeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$address': {
      id: '/$address'
      path: '/$address'
      fullPath: '/$address'
      preLoaderRoute: typeof AddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$tx': {
      id: '/card/$tx'
      path: '/card/$tx'
      fullPath: '/card/$tx'
      preLoaderRoute: typeof CardTxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sets/$game/$set': {
      id: '/sets/$game/$set'
      path: '/sets/$game/$set'
      fullPath: '/sets/$game/$set'
      preLoaderRoute: typeof SetsGameSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$game/$set/$card': {
      id: '/card/$game/$set/$card'
      path: '/card/$game/$set/$card'
      fullPath: '/card/$game/$set/$card'
      preLoaderRoute: typeof CardGameSetCardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressRoute: AddressRoute,
  BrowseRoute: BrowseRoute,
  EcosystemRoute: EcosystemRoute,
  FeaturedRoute: FeaturedRoute,
  MarketRoute: MarketRoute,
  PacksRoute: PacksRoute,
  PriceRoute: PriceRoute,
  SearchRoute: SearchRoute,
  StatsRoute: StatsRoute,
  TradesRoute: TradesRoute,
  CardTxRoute: CardTxRoute,
  SetsGameSetRoute: SetsGameSetRoute,
  CardGameSetCardRoute: CardGameSetCardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
